# Generated by Django 3.1.4 on 2020-12-30 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promoters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_form',
            name='followers',
            field=models.IntegerField(default=None),
        ),
    ]
