# Generated by Django 3.1.4 on 2021-01-24 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promoters', '0002_user_form_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_form',
            name='email',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
