# Generated by Django 3.1.4 on 2021-01-24 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promoters', '0005_auto_20210124_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_form',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
