# Generated by Django 3.1.4 on 2021-01-24 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promoters', '0007_auto_20210124_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_form',
            name='email2',
        ),
    ]
