# Generated by Django 3.1.4 on 2021-01-25 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promoters', '0008_remove_user_form_email2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_form',
            name='username',
        ),
        migrations.AddField(
            model_name='user_form',
            name='email',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='user_form',
            name='instagram_id',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='user_form',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default=None, max_length=1),
        ),
    ]
