# Generated by Django 3.1.4 on 2020-12-31 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company_form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('submission_date', models.DateTimeField(default=None)),
                ('verified', models.IntegerField(default=0)),
            ],
        ),
    ]
