# Generated by Django 3.1.4 on 2021-01-25 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_form',
            name='username',
        ),
        migrations.AddField(
            model_name='company_form',
            name='company_business_area',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='company_form',
            name='company_instagram_id',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='company_form',
            name='company_size',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='company_form',
            name='email',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='company_form',
            name='company_name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
