# Generated by Django 3.1.3 on 2021-01-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='type_client',
            field=models.CharField(choices=[('P', 'Promoter'), ('C', 'Company')], default=0, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
